# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3025ad2a8ba87b06373e33c004e922f04a040510cfb6c97ef754867f1044e8f7aea102ce07a2cde46ec1403e2f143079b932bfaee074622bc266074a9314fb12

test:
  secret_key_base: b4a23e5844e454f69389a0de4291af9ec53fdd6822e5909167a7815df88f8452cd2d1e4d4155c491ff159ea86e2ba9ccaf53caef8c21adf2c8cf4ccb0a86a1e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
